
import 'tailwindcss/tailwind.css'

import Head from 'next/head'
import Hero from '../components/Hero'
import SearchSection from '../components/SearchSection'
import { exercisesOptions, getData } from '../services'
import { useEffect, useRef, useState } from 'react'
import Exercises from '../components/Exercises'

export default function Home({ bodyPartList, exercises }) {
  const [selectedBodyPart, setSelectedBodyPart] = useState('all')
  const [prevSelectedBodyPart, setPrevSelectedBodyPart] = useState('all')
  const [exercisesByBodyPart, setExercisesByBodyPart] = useState([])
  const [searchedExercises, setSearchedExercises] = useState([])
  const [searchValue, setSearchValue] = useState('');
  let prevBodyPart = useRef('')
  prevBodyPart.current = selectedBodyPart
  useEffect(() => {
    async function main() {
      if (selectedBodyPart === 'all') return

      if (prevSelectedBodyPart === selectedBodyPart) return
      try {
        console.log('entered')
        await getData(`https://exercisedb.p.rapidapi.com/exercises/bodyPart/${selectedBodyPart}`,
          exercisesOptions
        ).then(data => setExercisesByBodyPart(data));
      } catch (error) {
        console.log(error)
      }
    }
    main()
  }, [selectedBodyPart, prevSelectedBodyPart])
  return (
    <div className="">
      <Head>
        <title>I GYM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.jpg" />
      </Head>
      <Hero />
      <SearchSection searchValue={searchValue} exercises={exercises} setSearchValue={setSearchValue} setSearchedExercises={setSearchedExercises} setPrevSelectedBodyPart={setPrevSelectedBodyPart} prevBodyPart={prevBodyPart} setSelectedBodyPart={setSelectedBodyPart} bodyParts={bodyPartList} />
      <Exercises data={searchValue ? searchedExercises : selectedBodyPart === 'all' ? exercises : exercisesByBodyPart} />
      <footer className='text-center font-semibold p-10 bg-black'>Made With Love By Oussama Bennabi  </footer>

    </div>
  )
}

export const getStaticProps = async () => {
  const bodyPartList = await getData(
    'https://exercisedb.p.rapidapi.com/exercises/bodyPartList',
    exercisesOptions
  ).then(data => data);
  const exercises = await getData(
    'https://exercisedb.p.rapidapi.com/exercises',
    exercisesOptions
  ).then(data => data);

  return {
    props: {
      bodyPartList,
      exercises
    }
  }
};
